### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by meLuiiiz** [meLuiiiz/uchat#1]
- [ ] AntiFlood (Plugin System)
- [ ] AntiSpam (Plugin System)
- [ ] Caracters Limit

- [ ] Fix Received Message by ScrollBottom
- [ ] Change Files Organization
